main: 
	g++ -o main main.cpp ConcatStringList.cpp  -I . -std=c++11 && ./main && rm -f ./main

checktest:
	g++ -o check ConcatStringList.cpp  CSL_checktestcase.cpp  -I . -std=c++11 && ./check && rm -f ./check
